# Generated by Django 3.1 on 2020-08-19 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='Imię')),
                ('lastName', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('about', models.TextField(blank=True, verbose_name='O')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Zdjęcie')),
            ],
            options={
                'verbose_name': 'Autor',
                'ordering': ['firstName', 'lastName'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title', 'headline'], 'verbose_name': 'Artykuł'},
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='obraz'),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.TextField(verbose_name='nagłówek'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(verbose_name='data publikacji'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='tekst'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='tytuł'),
        ),
        migrations.AddField(
            model_name='article',
            name='AuthorID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='articles.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='categoryID',
            field=models.ManyToManyField(to='articles.Category'),
        ),
    ]
