# Generated by Django 3.1 on 2020-08-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200819_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['published_at', 'title'], 'verbose_name': 'Artykuł', 'verbose_name_plural': 'Artykuły'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['firstName', 'lastName'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autorzy'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
    ]
